version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=iqoption
      - DB_PW=1234
      - DB_DB=iqoption_db
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=iqoption
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=iqoption_db
